include $(TOPDIR)/rules.mk

LUCI_TITLE:=ZH-Volt Maneger for Luci
LUCI_DEPENDS:=+luci-base +zh_volt

PKG_LICENSE:=MIT
PKG_MAINTAINER:=Matheus Sampaio Queiroha <srherobrine20@gmail.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature