#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

service_triggers() {
	procd_add_reload_trigger "zh-volt"
}

start_service() {
	config_load 'zh-volt'
	local netdev listen

	config_get netdev 'main' 'netdev' 'eth0'
	config_get listen 'main' 'listen' '/var/run/zh-volt.sock'

	rm -f "$sock_path"

	procd_open_instance

	procd_set_param command /usr/bin/zh_volt daemon "-i" "$netdev" "-l" "unix:$listen"
	procd_set_param netdev "$netdev"
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_set_param respawn
	procd_close_instance
}